# Generated by Django 2.2.5 on 2019-09-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_remove_user_following'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
