# Generated by Django 2.2.5 on 2019-09-14 14:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Team',
        ),
        migrations.RenameField(
            model_name='companygroup',
            old_name='company',
            new_name='team',
        ),
    ]
