# Generated by Django 2.2.5 on 2019-09-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_team_search_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='search_id',
            field=models.CharField(default='dkzpqbcjafeljcyuroui', max_length=40),
        ),
    ]
