# Generated by Django 2.2.3 on 2019-08-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_auto_20190830_1149'),
        ('main', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
