# Generated by Django 2.2.5 on 2019-09-14 18:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20190914_1506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupTask',
            new_name='TeamTask',
        ),
        migrations.DeleteModel(
            name='SingleTask',
        ),
    ]
