# Generated by Django 2.2.3 on 2019-08-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='singletask',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
