# Generated by Django 2.2.3 on 2019-08-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_singletask_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singletask',
            name='like',
        ),
    ]
