# Generated by Django 2.2.3 on 2019-09-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
