# Generated by Django 2.2.5 on 2019-09-14 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20190914_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='owner',
        ),
        migrations.AddField(
            model_name='teamtask',
            name='assignee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_todo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamtask',
            name='priority',
            field=models.CharField(choices=[('M', 'Medium'), ('H', 'High'), ('L', 'Low'), ('BE', 'Best effort')], default='M', max_length=2),
        ),
        migrations.AddField(
            model_name='teamtask',
            name='status',
            field=models.CharField(choices=[('DN', 'Done'), ('OD', 'On Doing'), ('ST', 'Stuck')], default='DN', max_length=2),
        ),
        migrations.AlterField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teamtask',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team_tasks', to='main.Team'),
        ),
        migrations.AlterField(
            model_name='teamtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
