# Generated by Django 2.2.5 on 2019-09-25 17:06

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190925_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='search_id',
            field=models.CharField(default='ehhjtiwyladuldlmnuqy', max_length=40),
        ),
        migrations.AlterField(
            model_name='teamtask',
            name='assignee',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='teamtask',
            name='status',
            field=models.CharField(choices=[('DN', 'Done'), ('OD', 'On Doing'), ('ST', 'Stuck')], default='OD', max_length=2),
        ),
    ]
