# Generated by Django 2.2.5 on 2019-09-17 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190914_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reqtou', to='main.Team'),
        ),
    ]
