# Generated by Django 2.2.3 on 2019-08-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190831_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouptask',
            old_name='passw',
            new_name='private_key',
        ),
        migrations.AddField(
            model_name='grouptask',
            name='public_key',
            field=models.CharField(default='1111', max_length=128),
        ),
    ]
