# Generated by Django 2.2.3 on 2019-08-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190831_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptask',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
