# Generated by Django 2.2.3 on 2019-09-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_grouptask_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptask',
            name='admin',
        ),
        migrations.AddField(
            model_name='grouptask',
            name='admin_key',
            field=models.CharField(default='2222', max_length=128),
        ),
    ]
