# Generated by Django 2.2.3 on 2019-09-01 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_auto_20190901_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptask',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
