# Generated by Django 2.2.3 on 2019-09-02 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_company_companygroup_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='companygroup',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companygroup',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_groups', to='main.Company'),
        ),
        migrations.AddField(
            model_name='companygroup',
            name='admin_key',
            field=models.CharField(default='1111', max_length=128),
        ),
        migrations.AddField(
            model_name='companygroup',
            name='member',
            field=models.ManyToManyField(related_name='group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companygroup',
            name='private_key',
            field=models.CharField(default='0000', max_length=128),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
