# Generated by Django 2.2.3 on 2019-09-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190902_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=256),
        ),
    ]
