# Generated by Django 2.2.3 on 2019-09-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_company_owner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=256, verbose_name='E-mail'),
        ),
    ]
