# Generated by Django 2.2.3 on 2019-09-03 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190903_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ManyToManyField(related_name='own_co', to=settings.AUTH_USER_MODEL),
        ),
    ]
