# Generated by Django 2.2.3 on 2019-09-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_company_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='owner_email',
            new_name='creator_email',
        ),
    ]
