# Generated by Django 2.2.3 on 2019-09-03 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190903_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ManyToManyField(related_name='co_own', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companygroup',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_own', to=settings.AUTH_USER_MODEL),
        ),
    ]
