# Generated by Django 2.2.3 on 2019-09-04 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0022_auto_20190903_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companygroup',
            name='member',
            field=models.ManyToManyField(related_name='groups_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
