# Generated by Django 2.2.3 on 2019-09-04 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0023_auto_20190904_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='secret_key',
            field=models.CharField(default='secret', max_length=128),
        ),
        migrations.RemoveField(
            model_name='company',
            name='employee',
        ),
        migrations.AddField(
            model_name='company',
            name='employee',
            field=models.ManyToManyField(related_name='workat', to=settings.AUTH_USER_MODEL),
        ),
    ]
